(deftheme juvi-dark
  "Created 2023-09-26. based on deeper-blue")

(custom-theme-set-faces
 'juvi-dark
 '(Info-title-1-face ((((class color) (min-colors 89)) (:family "helv" :weight bold :height 1.728))))
 '(Info-title-2-face ((((class color) (min-colors 89)) (:family "helv" :weight bold :height 1.44))))
 '(Info-title-3-face ((((class color) (min-colors 89)) (:family "helv" :weight bold :height 1.2))))
 '(Info-title-4-face ((((class color) (min-colors 89)) (:family "helv" :weight bold))))
 '(compilation-column-number ((((class color) (min-colors 89)) (:foreground "LightGreen"))))
 '(compilation-error ((((class color) (min-colors 89)) (:foreground "Red1"))))
 '(compilation-info ((((class color) (min-colors 89)) (:weight normal :foreground "LightSkyBlue"))))
 '(compilation-line-number ((((class color) (min-colors 89)) (:foreground "LightGreen"))))
 '(compilation-mode-line-exit ((((class color) (min-colors 89)) (:foreground "blue4"))))
 '(cperl-array-face ((((class color) (min-colors 89)) (:foreground "yellow2"))))
 '(cperl-hash-face ((((class color) (min-colors 89)) (:foreground "coral1"))))
 '(cursor ((((class color) (min-colors 89)) (:background "green"))))
 '(diff-context ((((class color) (min-colors 89)) (:foreground "seashell4"))))
 '(diff-file-header ((((class color) (min-colors 89)) (:background "grey60"))))
 '(diff-function ((((class color) (min-colors 89)) (:inherit diff-header))))
 '(diff-header ((((class color) (min-colors 89)) (:background "grey45"))))
 '(diff-hunk-header ((((class color) (min-colors 89)) (:inherit diff-header))))
 '(diff-index ((((class color) (min-colors 89)) (:inherit diff-file-header))))
 '(diff-indicator-added ((((class color) (min-colors 89)) (:foreground "white" :background "darkolivegreen"))))
 '(diff-indicator-changed ((((class color) (min-colors 89)) (:foreground "white" :background "dodgerblue4"))))
 '(diff-indicator-removed ((((class color) (min-colors 89)) (:foreground "white" :background "indianred4"))))
 '(diff-refine-change ((((class color) (min-colors 89)) (:background "skyblue4"))))
 '(dired-marked ((((class color) (min-colors 89)) (:background "dodgerblue3" :foreground "white"))))
 '(ediff-current-diff-A ((((class color) (min-colors 89)) (:background "green4" :foreground "white"))))
 '(ediff-current-diff-B ((((class color) (min-colors 89)) (:background "darkorange3" :foreground "white"))))
 '(ediff-even-diff-B ((((class color) (min-colors 89)) (:background "Grey50" :foreground "White"))))
 '(ediff-fine-diff-A ((((class color) (min-colors 89)) (:background "skyblue4" :foreground "white"))))
 '(ediff-fine-diff-B ((((class color) (min-colors 89)) (:background "cyan4" :foreground "white"))))
 '(ediff-odd-diff-A ((((class color) (min-colors 89)) (:background "Grey50" :foreground "White"))))
 '(error ((((class color) (min-colors 89)) (:foreground "red"))))
 '(flymake-error ((((class color) (min-colors 89)) (:background nil :underline "red"))))
 '(flymake-warning ((((class color) (min-colors 89)) (:background nil :underline "magenta3"))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "LightCoral"))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 89)) (:foreground "gray50"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "gray50"))))
 '(font-lock-constant-face ((t (:foreground "#7E9B41"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "moccasin"))))
 '(font-lock-function-name-face ((t (:foreground "#9C6D00"))))
 '(font-lock-keyword-face ((t (:foreground "#008DBC"))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "gold"))))
 '(font-lock-reference-face ((((class color) (min-colors 89)) (:foreground "LightCoral"))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 89)) (:weight bold))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 89)) (:weight bold))))
 '(font-lock-string-face ((t (:foreground "#BC8747"))))
 '(font-lock-type-face ((t (:foreground "#00AEC1"))))
 '(font-lock-variable-name-face ((t (:foreground "#21A75C"))))
 '(fringe ((((class color) (min-colors 89)) (:background "black"))))
 '(highlight ((((class color) (min-colors 89)) (:background "DodgerBlue4"))))
 '(ido-first-match ((((class color) (min-colors 89)) (:weight normal :foreground "orange"))))
 '(ido-only-match ((((class color) (min-colors 89)) (:foreground "green"))))
 '(ido-subdir ((((class color) (min-colors 89)) (:foreground nil :inherit font-lock-keyword-face))))
 '(info-header-node ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1"))))
 '(info-header-xref ((((class color) (min-colors 89)) (:foreground "SeaGreen2"))))
 '(info-menu-header ((((class color) (min-colors 89)) (:family "helv" :weight bold))))
 '(info-node ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1"))))
 '(info-xref ((((class color) (min-colors 89)) (:foreground "SeaGreen2"))))
 '(isearch ((((class color) (min-colors 89)) (:background "coral2" :foreground "white"))))
 '(isearch-lazy-highlight-face ((((class color) (min-colors 89)) (:background "coral4" :foreground "white"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:background "cadetblue" :foreground "white"))))
 '(match ((((class color) (min-colors 89)) (:background "DeepPink4"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "CadetBlue1"))))
 '(mode-line ((((class color) (min-colors 89)) (:background "gray75" :foreground "black" :box (:line-width 1 :style released-button)))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:weight bold :background nil :foreground "blue4"))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:background "gray40" :foreground "black" :box (:line-width 1 :color "gray40" :style nil)))))
 '(outline-1 ((((class color) (min-colors 89)) (:foreground "SkyBlue1"))))
 '(outline-2 ((((class color) (min-colors 89)) (:foreground "CadetBlue1"))))
 '(outline-3 ((((class color) (min-colors 89)) (:foreground "LightSteelBlue1"))))
 '(outline-4 ((((class color) (min-colors 89)) (:foreground "turquoise2"))))
 '(outline-5 ((((class color) (min-colors 89)) (:foreground "aquamarine1"))))
 '(primary-selection ((((class color) (min-colors 89)) (:background "blue3"))))
 '(region ((((class color) (min-colors 89)) (:background "#103050"))))
 '(show-paren-match-face ((((class color) (min-colors 89)) (:background "dodgerblue1" :foreground "white"))))
 '(show-paren-mismatch-face ((((class color) (min-colors 89)) (:background "red1" :foreground "white"))))
 '(success ((((class color) (min-colors 89)) (:foreground "SeaGreen2"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "Yellow"))))
 '(highlight-symbol-face ((t (:background "forest green" :foreground "gray100"))))
 '(default ((t (:background "#000000" :foreground "gray50"))))
 '(widget-field ((t (:extend t :background "#282828"))))
 '(clojure-keyword-face ((t (:inherit font-lock-constant-face)))))

(provide-theme 'juvi-dark)
